<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonMenu</name>
   <tag></tag>
   <elementGuidId>736e7cc7-088c-4935-b10f-858e44b6e8c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@role='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.-tertiary.g_id_signout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>890b9f0b-ea7f-4095-967b-4a3d76c46dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://account.kompas.com/logout/VlZadk1GbHJkRzlOUlVvd1VXNVZjbEpyU1RWTlJXTTFVa2hhUzFJelRYbFVhbVJyVmxoS2JsRjZhRXBsVlUwMFVrWldObGRGVmtaV1dFSlNZa1ZhVEU1SVVrMVpiRTEzVFZWa1dWVXlSVEZoYkZKQ1pXMXdWV0ZJUmxwTE1VWldWVVZvV1dSdFVubFZWbFp0VmtVNVRHVlhZemxRVVQwOQ==/aHR0cHM6Ly93d3cua29tcGFzLmNvbT9sZ25fbWV0aG9kPWtvbXBhc2lkJmw9Yw==?revoke=active</value>
      <webElementGuid>7e804abc-0b4d-4f80-aa02-ec1dc91d2bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button -tertiary g_id_signout</value>
      <webElementGuid>5aff3609-6995-4080-b0c7-10ace3b0359a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>google.accounts.id.disableAutoSelect(); return true;</value>
      <webElementGuid>c3a41b38-a467-413e-9603-8957c5ca8696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>a703001a-a224-40ca-8abc-63046f8d3606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kgmDialog-confirm-logout&quot;)/div[@class=&quot;kgmDialog-block&quot;]/div[@class=&quot;kgmDialog-footer --cta&quot;]/a[@class=&quot;button -tertiary g_id_signout&quot;]</value>
      <webElementGuid>a7d9ae4a-e555-4b62-80e5-53623b8d6c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='google.accounts.id.disableAutoSelect(); return true;']</value>
      <webElementGuid>2c40a4fd-4930-4325-b4e1-3f0b497d02d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kgmDialog-confirm-logout']/div/div[3]/a</value>
      <webElementGuid>28cbe294-09ad-42da-ab94-8c335442f360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Logout')])[2]</value>
      <webElementGuid>5761544a-f291-49bf-aab8-0db1b2635119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Logout'])[1]/following::a[1]</value>
      <webElementGuid>5cff8260-f491-4975-ba15-77a946b6c6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[1]/following::a[1]</value>
      <webElementGuid>ef1a6e2c-b97e-416f-9b20-036b57e0b413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan dan Logout'])[1]/preceding::a[1]</value>
      <webElementGuid>60cba1a4-c87c-4700-9991-c880b2c4d88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://account.kompas.com/logout/VlZadk1GbHJkRzlOUlVvd1VXNVZjbEpyU1RWTlJXTTFVa2hhUzFJelRYbFVhbVJyVmxoS2JsRjZhRXBsVlUwMFVrWldObGRGVmtaV1dFSlNZa1ZhVEU1SVVrMVpiRTEzVFZWa1dWVXlSVEZoYkZKQ1pXMXdWV0ZJUmxwTE1VWldWVVZvV1dSdFVubFZWbFp0VmtVNVRHVlhZemxRVVQwOQ==/aHR0cHM6Ly93d3cua29tcGFzLmNvbT9sZ25fbWV0aG9kPWtvbXBhc2lkJmw9Yw==?revoke=active')]</value>
      <webElementGuid>6e663aa0-a632-4df3-9999-8cac7932f1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a</value>
      <webElementGuid>9c149968-52a5-4ecc-a42a-784e22e9c3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://account.kompas.com/logout/VlZadk1GbHJkRzlOUlVvd1VXNVZjbEpyU1RWTlJXTTFVa2hhUzFJelRYbFVhbVJyVmxoS2JsRjZhRXBsVlUwMFVrWldObGRGVmtaV1dFSlNZa1ZhVEU1SVVrMVpiRTEzVFZWa1dWVXlSVEZoYkZKQ1pXMXdWV0ZJUmxwTE1VWldWVVZvV1dSdFVubFZWbFp0VmtVNVRHVlhZemxRVVQwOQ==/aHR0cHM6Ly93d3cua29tcGFzLmNvbT9sZ25fbWV0aG9kPWtvbXBhc2lkJmw9Yw==?revoke=active' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>d93c1da5-c56d-4269-abe4-7a8c04073a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
