<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconProfile</name>
   <tag></tag>
   <elementGuidId>fa0b725d-27b5-43a9-89d8-5bbe8228fd21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sso__icon__login_top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='sso__icon__login_top']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e5d19de9-bf57-4f88-85ba-4e33dc40af0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sso__icon__login sso__avatar</value>
      <webElementGuid>1a5d98d2-6b23-4db6-b6cf-45587ca84a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sso__icon__login_top</value>
      <webElementGuid>e6064019-cc7c-4849-9d48-91af946d1076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-avatar</name>
      <type>Main</type>
      <value>bg</value>
      <webElementGuid>662912b6-e92d-47c5-b3b1-5cd2f8e59618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-init</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>e4223d64-46c6-455e-81ea-04d0f2ca9d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sso__icon__login_top&quot;)</value>
      <webElementGuid>1f1a034c-9875-4670-b109-d8b1e14d77e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='sso__icon__login_top']</value>
      <webElementGuid>11757fc3-28b0-424d-bb33-85d138325767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>ecf796b0-2bcd-437c-aad3-8f17753ff68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'sso__icon__login_top']</value>
      <webElementGuid>66543125-817d-41ea-8672-78df73365f0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
